/*
 * File: COM_SW_Standalone.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 *
 * Created: Thu Nov 09 14:34:43 2023
 */

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                COM_SW_Standalone

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     7

/* Input Port  0 */
#define IN_PORT_0_NAME                 HALL_1
#define INPUT_0_WIDTH                  1
#define INPUT_DIMS_0_COL               1
#define INPUT_0_DTYPE                  boolean_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define IN_0_FRAME_BASED               FRAME_NO
#define IN_0_BUS_BASED                 0
#define IN_0_BUS_NAME
#define IN_0_DIMS                      1-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  0
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            9
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125

/* Input Port  1 */
#define IN_PORT_1_NAME                 HALL_2
#define INPUT_1_WIDTH                  1
#define INPUT_DIMS_1_COL               1
#define INPUT_1_DTYPE                  boolean_T
#define INPUT_1_COMPLEX                COMPLEX_NO
#define IN_1_FRAME_BASED               FRAME_NO
#define IN_1_BUS_BASED                 0
#define IN_1_BUS_NAME
#define IN_1_DIMS                      1-D
#define INPUT_1_FEEDTHROUGH            1
#define IN_1_ISSIGNED                  0
#define IN_1_WORDLENGTH                8
#define IN_1_FIXPOINTSCALING           1
#define IN_1_FRACTIONLENGTH            9
#define IN_1_BIAS                      0
#define IN_1_SLOPE                     0.125

/* Input Port  2 */
#define IN_PORT_2_NAME                 HALL_3
#define INPUT_2_WIDTH                  1
#define INPUT_DIMS_2_COL               1
#define INPUT_2_DTYPE                  boolean_T
#define INPUT_2_COMPLEX                COMPLEX_NO
#define IN_2_FRAME_BASED               FRAME_NO
#define IN_2_BUS_BASED                 0
#define IN_2_BUS_NAME
#define IN_2_DIMS                      1-D
#define INPUT_2_FEEDTHROUGH            1
#define IN_2_ISSIGNED                  0
#define IN_2_WORDLENGTH                8
#define IN_2_FIXPOINTSCALING           1
#define IN_2_FRACTIONLENGTH            9
#define IN_2_BIAS                      0
#define IN_2_SLOPE                     0.125

/* Input Port  3 */
#define IN_PORT_3_NAME                 Output_Shaft_Sensor
#define INPUT_3_WIDTH                  1
#define INPUT_DIMS_3_COL               1
#define INPUT_3_DTYPE                  uint8_T
#define INPUT_3_COMPLEX                COMPLEX_NO
#define IN_3_FRAME_BASED               FRAME_NO
#define IN_3_BUS_BASED                 0
#define IN_3_BUS_NAME
#define IN_3_DIMS                      1-D
#define INPUT_3_FEEDTHROUGH            1
#define IN_3_ISSIGNED                  0
#define IN_3_WORDLENGTH                8
#define IN_3_FIXPOINTSCALING           1
#define IN_3_FRACTIONLENGTH            9
#define IN_3_BIAS                      0
#define IN_3_SLOPE                     0.125

/* Input Port  4 */
#define IN_PORT_4_NAME                 Power_Supply
#define INPUT_4_WIDTH                  1
#define INPUT_DIMS_4_COL               1
#define INPUT_4_DTYPE                  uint8_T
#define INPUT_4_COMPLEX                COMPLEX_NO
#define IN_4_FRAME_BASED               FRAME_NO
#define IN_4_BUS_BASED                 0
#define IN_4_BUS_NAME
#define IN_4_DIMS                      1-D
#define INPUT_4_FEEDTHROUGH            1
#define IN_4_ISSIGNED                  0
#define IN_4_WORDLENGTH                8
#define IN_4_FIXPOINTSCALING           1
#define IN_4_FRACTIONLENGTH            9
#define IN_4_BIAS                      0
#define IN_4_SLOPE                     0.125

/* Input Port  5 */
#define IN_PORT_5_NAME                 MON_to_COM
#define INPUT_5_WIDTH                  1
#define INPUT_DIMS_5_COL               1
#define INPUT_5_DTYPE                  uint8_T
#define INPUT_5_COMPLEX                COMPLEX_NO
#define IN_5_FRAME_BASED               FRAME_NO
#define IN_5_BUS_BASED                 0
#define IN_5_BUS_NAME
#define IN_5_DIMS                      1-D
#define INPUT_5_FEEDTHROUGH            1
#define IN_5_ISSIGNED                  0
#define IN_5_WORDLENGTH                8
#define IN_5_FIXPOINTSCALING           1
#define IN_5_FRACTIONLENGTH            9
#define IN_5_BIAS                      0
#define IN_5_SLOPE                     0.125

/* Input Port  6 */
#define IN_PORT_6_NAME                 Prot_to_COM_input
#define INPUT_6_WIDTH                  1
#define INPUT_DIMS_6_COL               1
#define INPUT_6_DTYPE                  uint8_T
#define INPUT_6_COMPLEX                COMPLEX_NO
#define IN_6_FRAME_BASED               FRAME_NO
#define IN_6_BUS_BASED                 0
#define IN_6_BUS_NAME
#define IN_6_DIMS                      1-D
#define INPUT_6_FEEDTHROUGH            1
#define IN_6_ISSIGNED                  0
#define IN_6_WORDLENGTH                8
#define IN_6_FIXPOINTSCALING           1
#define IN_6_FRACTIONLENGTH            9
#define IN_6_BIAS                      0
#define IN_6_SLOPE                     0.125
#define NUM_OUTPUTS                    11

/* Output Port  0 */
#define OUT_PORT_0_NAME                COM_to_MON
#define OUTPUT_0_WIDTH                 1
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 uint8_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUT_0_FRAME_BASED              FRAME_NO
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     1-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125

/* Output Port  1 */
#define OUT_PORT_1_NAME                COM_to_Prot
#define OUTPUT_1_WIDTH                 1
#define OUTPUT_DIMS_1_COL              1
#define OUTPUT_1_DTYPE                 boolean_T
#define OUTPUT_1_COMPLEX               COMPLEX_NO
#define OUT_1_FRAME_BASED              FRAME_NO
#define OUT_1_BUS_BASED                0
#define OUT_1_BUS_NAME
#define OUT_1_DIMS                     1-D
#define OUT_1_ISSIGNED                 1
#define OUT_1_WORDLENGTH               8
#define OUT_1_FIXPOINTSCALING          1
#define OUT_1_FRACTIONLENGTH           3
#define OUT_1_BIAS                     0
#define OUT_1_SLOPE                    0.125

/* Output Port  2 */
#define OUT_PORT_2_NAME                Output_IN_1
#define OUTPUT_2_WIDTH                 1
#define OUTPUT_DIMS_2_COL              1
#define OUTPUT_2_DTYPE                 boolean_T
#define OUTPUT_2_COMPLEX               COMPLEX_NO
#define OUT_2_FRAME_BASED              FRAME_NO
#define OUT_2_BUS_BASED                0
#define OUT_2_BUS_NAME
#define OUT_2_DIMS                     1-D
#define OUT_2_ISSIGNED                 1
#define OUT_2_WORDLENGTH               8
#define OUT_2_FIXPOINTSCALING          1
#define OUT_2_FRACTIONLENGTH           3
#define OUT_2_BIAS                     0
#define OUT_2_SLOPE                    0.125

/* Output Port  3 */
#define OUT_PORT_3_NAME                Output_IN_2
#define OUTPUT_3_WIDTH                 1
#define OUTPUT_DIMS_3_COL              1
#define OUTPUT_3_DTYPE                 boolean_T
#define OUTPUT_3_COMPLEX               COMPLEX_NO
#define OUT_3_FRAME_BASED              FRAME_NO
#define OUT_3_BUS_BASED                0
#define OUT_3_BUS_NAME
#define OUT_3_DIMS                     1-D
#define OUT_3_ISSIGNED                 1
#define OUT_3_WORDLENGTH               8
#define OUT_3_FIXPOINTSCALING          1
#define OUT_3_FRACTIONLENGTH           3
#define OUT_3_BIAS                     0
#define OUT_3_SLOPE                    0.125

/* Output Port  4 */
#define OUT_PORT_4_NAME                Output_IN_3
#define OUTPUT_4_WIDTH                 1
#define OUTPUT_DIMS_4_COL              1
#define OUTPUT_4_DTYPE                 boolean_T
#define OUTPUT_4_COMPLEX               COMPLEX_NO
#define OUT_4_FRAME_BASED              FRAME_NO
#define OUT_4_BUS_BASED                0
#define OUT_4_BUS_NAME
#define OUT_4_DIMS                     1-D
#define OUT_4_ISSIGNED                 1
#define OUT_4_WORDLENGTH               8
#define OUT_4_FIXPOINTSCALING          1
#define OUT_4_FRACTIONLENGTH           3
#define OUT_4_BIAS                     0
#define OUT_4_SLOPE                    0.125

/* Output Port  5 */
#define OUT_PORT_5_NAME                Output_EN_1
#define OUTPUT_5_WIDTH                 1
#define OUTPUT_DIMS_5_COL              1
#define OUTPUT_5_DTYPE                 boolean_T
#define OUTPUT_5_COMPLEX               COMPLEX_NO
#define OUT_5_FRAME_BASED              FRAME_NO
#define OUT_5_BUS_BASED                0
#define OUT_5_BUS_NAME
#define OUT_5_DIMS                     1-D
#define OUT_5_ISSIGNED                 1
#define OUT_5_WORDLENGTH               8
#define OUT_5_FIXPOINTSCALING          1
#define OUT_5_FRACTIONLENGTH           3
#define OUT_5_BIAS                     0
#define OUT_5_SLOPE                    0.125

/* Output Port  6 */
#define OUT_PORT_6_NAME                Output_EN_2
#define OUTPUT_6_WIDTH                 1
#define OUTPUT_DIMS_6_COL              1
#define OUTPUT_6_DTYPE                 boolean_T
#define OUTPUT_6_COMPLEX               COMPLEX_NO
#define OUT_6_FRAME_BASED              FRAME_NO
#define OUT_6_BUS_BASED                0
#define OUT_6_BUS_NAME
#define OUT_6_DIMS                     1-D
#define OUT_6_ISSIGNED                 1
#define OUT_6_WORDLENGTH               8
#define OUT_6_FIXPOINTSCALING          1
#define OUT_6_FRACTIONLENGTH           3
#define OUT_6_BIAS                     0
#define OUT_6_SLOPE                    0.125

/* Output Port  7 */
#define OUT_PORT_7_NAME                Output_EN_3
#define OUTPUT_7_WIDTH                 1
#define OUTPUT_DIMS_7_COL              1
#define OUTPUT_7_DTYPE                 boolean_T
#define OUTPUT_7_COMPLEX               COMPLEX_NO
#define OUT_7_FRAME_BASED              FRAME_NO
#define OUT_7_BUS_BASED                0
#define OUT_7_BUS_NAME
#define OUT_7_DIMS                     1-D
#define OUT_7_ISSIGNED                 1
#define OUT_7_WORDLENGTH               8
#define OUT_7_FIXPOINTSCALING          1
#define OUT_7_FRACTIONLENGTH           3
#define OUT_7_BIAS                     0
#define OUT_7_SLOPE                    0.125

/* Output Port  8 */
#define OUT_PORT_8_NAME                DBG_POST_CMD
#define OUTPUT_8_WIDTH                 1
#define OUTPUT_DIMS_8_COL              1
#define OUTPUT_8_DTYPE                 uint8_T
#define OUTPUT_8_COMPLEX               COMPLEX_NO
#define OUT_8_FRAME_BASED              FRAME_NO
#define OUT_8_BUS_BASED                0
#define OUT_8_BUS_NAME
#define OUT_8_DIMS                     1-D
#define OUT_8_ISSIGNED                 1
#define OUT_8_WORDLENGTH               8
#define OUT_8_FIXPOINTSCALING          1
#define OUT_8_FRACTIONLENGTH           3
#define OUT_8_BIAS                     0
#define OUT_8_SLOPE                    0.125

/* Output Port  9 */
#define OUT_PORT_9_NAME                DBG_POST_ERROR
#define OUTPUT_9_WIDTH                 1
#define OUTPUT_DIMS_9_COL              1
#define OUTPUT_9_DTYPE                 uint8_T
#define OUTPUT_9_COMPLEX               COMPLEX_NO
#define OUT_9_FRAME_BASED              FRAME_NO
#define OUT_9_BUS_BASED                0
#define OUT_9_BUS_NAME
#define OUT_9_DIMS                     1-D
#define OUT_9_ISSIGNED                 1
#define OUT_9_WORDLENGTH               8
#define OUT_9_FIXPOINTSCALING          1
#define OUT_9_FRACTIONLENGTH           3
#define OUT_9_BIAS                     0
#define OUT_9_SLOPE                    0.125

/* Output Port  10 */
#define OUT_PORT_10_NAME               DBG_CRC
#define OUTPUT_10_WIDTH                1
#define OUTPUT_DIMS_10_COL             1
#define OUTPUT_10_DTYPE                uint8_T
#define OUTPUT_10_COMPLEX              COMPLEX_NO
#define OUT_10_FRAME_BASED             FRAME_NO
#define OUT_10_BUS_BASED               0
#define OUT_10_BUS_NAME
#define OUT_10_DIMS                    1-D
#define OUT_10_ISSIGNED                1
#define OUT_10_WORDLENGTH              8
#define OUT_10_FIXPOINTSCALING         1
#define OUT_10_FRACTIONLENGTH          3
#define OUT_10_BIAS                    0
#define OUT_10_SLOPE                   0.125
#define NPARAMS                        0
#define SAMPLE_TIME_0                  INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES                0
#define DISC_STATES_IC                 [0]
#define NUM_CONT_STATES                0
#define CONT_STATES_IC                 [0]
#define SFUNWIZ_GENERATE_TLC           0
#define SOURCEFILES                    "__SFB__SRC_PATH pwd__SFB__SRC_PATH src_path_0__SFB__LIB_PATH C:\Users\berna\13_COM_SW\driver__SFB__libThalesCom.a__SFB__Driver_AS5045.c__SFB__Driver_GPIO.c__SFB__Driver_BLDC.c__SFB__Driver_CLK.c__SFB__Driver_Serial.c__SFB__Driver_Temp.c__SFB__main.c__SFB__Driver_Position.c__SFB__"
#define PANELINDEX                     N/A
#define USE_SIMSTRUCT                  1
#define SHOW_COMPILE_STEPS             0
#define CREATE_DEBUG_MEXFILE           0
#define SAVE_CODE_ONLY                 0
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"

extern void COM_SW_Standalone_Start_wrapper(SimStruct *S);
extern void COM_SW_Standalone_Outputs_wrapper(const boolean_T *HALL_1,
  const boolean_T *HALL_2,
  const boolean_T *HALL_3,
  const uint8_T *Output_Shaft_Sensor,
  const uint8_T *Power_Supply,
  const uint8_T *MON_to_COM,
  const uint8_T *Prot_to_COM_input,
  uint8_T *COM_to_MON,
  boolean_T *COM_to_Prot,
  boolean_T *Output_IN_1,
  boolean_T *Output_IN_2,
  boolean_T *Output_IN_3,
  boolean_T *Output_EN_1,
  boolean_T *Output_EN_2,
  boolean_T *Output_EN_3,
  uint8_T *DBG_POST_CMD,
  uint8_T *DBG_POST_ERROR,
  uint8_T *DBG_CRC,
  SimStruct *S);

/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(inputDimsInfo);
  DECL_AND_INIT_DIMSINFO(outputDimsInfo);
  ssSetNumSFcnParams(S, NPARAMS);
  if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
    return;                            /* Parameter mismatch will be reported by Simulink */
  }

  ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);
  ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);
  ssSetNumContStates(S, NUM_CONT_STATES);
  ssSetNumDiscStates(S, NUM_DISC_STATES);
  if (!ssSetNumInputPorts(S, NUM_INPUTS))
    return;

  /* Input Port 0 */
  ssSetInputPortWidth(S, 0, INPUT_0_WIDTH);
  ssSetInputPortDataType(S, 0, SS_BOOLEAN);
  ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/

  /* Input Port 1 */
  ssSetInputPortWidth(S, 1, INPUT_1_WIDTH);
  ssSetInputPortDataType(S, 1, SS_BOOLEAN);
  ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 1, 1);/*direct input signal access*/

  /* Input Port 2 */
  ssSetInputPortWidth(S, 2, INPUT_2_WIDTH);
  ssSetInputPortDataType(S, 2, SS_BOOLEAN);
  ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 2, 1);/*direct input signal access*/

  /* Input Port 3 */
  ssSetInputPortWidth(S, 3, INPUT_3_WIDTH);
  ssSetInputPortDataType(S, 3, SS_UINT8);
  ssSetInputPortComplexSignal(S, 3, INPUT_3_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 3, 1);/*direct input signal access*/

  /* Input Port 4 */
  ssSetInputPortWidth(S, 4, INPUT_4_WIDTH);
  ssSetInputPortDataType(S, 4, SS_UINT8);
  ssSetInputPortComplexSignal(S, 4, INPUT_4_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 4, INPUT_4_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 4, 1);/*direct input signal access*/

  /* Input Port 5 */
  ssSetInputPortWidth(S, 5, INPUT_5_WIDTH);
  ssSetInputPortDataType(S, 5, SS_UINT8);
  ssSetInputPortComplexSignal(S, 5, INPUT_5_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 5, INPUT_5_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 5, 1);/*direct input signal access*/

  /* Input Port 6 */
  ssSetInputPortWidth(S, 6, INPUT_6_WIDTH);
  ssSetInputPortDataType(S, 6, SS_UINT8);
  ssSetInputPortComplexSignal(S, 6, INPUT_6_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 6, INPUT_6_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 6, 1);/*direct input signal access*/
  if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
    return;

  /* Output Port 0 */
  ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
  ssSetOutputPortDataType(S, 0, SS_UINT8);
  ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

  /* Output Port 1 */
  ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
  ssSetOutputPortDataType(S, 1, SS_BOOLEAN);
  ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);

  /* Output Port 2 */
  ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
  ssSetOutputPortDataType(S, 2, SS_BOOLEAN);
  ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);

  /* Output Port 3 */
  ssSetOutputPortWidth(S, 3, OUTPUT_3_WIDTH);
  ssSetOutputPortDataType(S, 3, SS_BOOLEAN);
  ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);

  /* Output Port 4 */
  ssSetOutputPortWidth(S, 4, OUTPUT_4_WIDTH);
  ssSetOutputPortDataType(S, 4, SS_BOOLEAN);
  ssSetOutputPortComplexSignal(S, 4, OUTPUT_4_COMPLEX);

  /* Output Port 5 */
  ssSetOutputPortWidth(S, 5, OUTPUT_5_WIDTH);
  ssSetOutputPortDataType(S, 5, SS_BOOLEAN);
  ssSetOutputPortComplexSignal(S, 5, OUTPUT_5_COMPLEX);

  /* Output Port 6 */
  ssSetOutputPortWidth(S, 6, OUTPUT_6_WIDTH);
  ssSetOutputPortDataType(S, 6, SS_BOOLEAN);
  ssSetOutputPortComplexSignal(S, 6, OUTPUT_6_COMPLEX);

  /* Output Port 7 */
  ssSetOutputPortWidth(S, 7, OUTPUT_7_WIDTH);
  ssSetOutputPortDataType(S, 7, SS_BOOLEAN);
  ssSetOutputPortComplexSignal(S, 7, OUTPUT_7_COMPLEX);

  /* Output Port 8 */
  ssSetOutputPortWidth(S, 8, OUTPUT_8_WIDTH);
  ssSetOutputPortDataType(S, 8, SS_UINT8);
  ssSetOutputPortComplexSignal(S, 8, OUTPUT_8_COMPLEX);

  /* Output Port 9 */
  ssSetOutputPortWidth(S, 9, OUTPUT_9_WIDTH);
  ssSetOutputPortDataType(S, 9, SS_UINT8);
  ssSetOutputPortComplexSignal(S, 9, OUTPUT_9_COMPLEX);

  /* Output Port 10 */
  ssSetOutputPortWidth(S, 10, OUTPUT_10_WIDTH);
  ssSetOutputPortDataType(S, 10, SS_UINT8);
  ssSetOutputPortComplexSignal(S, 10, OUTPUT_10_COMPLEX);
  ssSetNumPWork(S, 0);
  ssSetNumSampleTimes(S, 1);
  ssSetNumRWork(S, 0);
  ssSetNumIWork(S, 0);
  ssSetNumModes(S, 0);
  ssSetNumNonsampledZCs(S, 0);
  ssSetSimulinkVersionGeneratedIn(S, "10.4");

  /* Take care when specifying exception free code - see sfuntmpl_doc.c */
  ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                   SS_OPTION_WORKS_WITH_CODE_REUSE));
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, SAMPLE_TIME_0);
  ssSetModelReferenceSampleTimeDefaultInheritance(S);
  ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_START                                                /* Change to #undef to remove function */
#if defined(MDL_START)

/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
  COM_SW_Standalone_Start_wrapper(S);
}

#endif                                 /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  const boolean_T *HALL_1 = (boolean_T *) ssGetInputPortRealSignal(S, 0);
  const boolean_T *HALL_2 = (boolean_T *) ssGetInputPortRealSignal(S, 1);
  const boolean_T *HALL_3 = (boolean_T *) ssGetInputPortRealSignal(S, 2);
  const uint8_T *Output_Shaft_Sensor = (uint8_T *) ssGetInputPortRealSignal(S, 3);
  const uint8_T *Power_Supply = (uint8_T *) ssGetInputPortRealSignal(S, 4);
  const uint8_T *MON_to_COM = (uint8_T *) ssGetInputPortRealSignal(S, 5);
  const uint8_T *Prot_to_COM_input = (uint8_T *) ssGetInputPortRealSignal(S, 6);
  uint8_T *COM_to_MON = (uint8_T *) ssGetOutputPortRealSignal(S, 0);
  boolean_T *COM_to_Prot = (boolean_T *) ssGetOutputPortRealSignal(S, 1);
  boolean_T *Output_IN_1 = (boolean_T *) ssGetOutputPortRealSignal(S, 2);
  boolean_T *Output_IN_2 = (boolean_T *) ssGetOutputPortRealSignal(S, 3);
  boolean_T *Output_IN_3 = (boolean_T *) ssGetOutputPortRealSignal(S, 4);
  boolean_T *Output_EN_1 = (boolean_T *) ssGetOutputPortRealSignal(S, 5);
  boolean_T *Output_EN_2 = (boolean_T *) ssGetOutputPortRealSignal(S, 6);
  boolean_T *Output_EN_3 = (boolean_T *) ssGetOutputPortRealSignal(S, 7);
  uint8_T *DBG_POST_CMD = (uint8_T *) ssGetOutputPortRealSignal(S, 8);
  uint8_T *DBG_POST_ERROR = (uint8_T *) ssGetOutputPortRealSignal(S, 9);
  uint8_T *DBG_CRC = (uint8_T *) ssGetOutputPortRealSignal(S, 10);
  COM_SW_Standalone_Outputs_wrapper(HALL_1, HALL_2, HALL_3, Output_Shaft_Sensor,
    Power_Supply, MON_to_COM, Prot_to_COM_input, COM_to_MON, COM_to_Prot,
    Output_IN_1, Output_IN_2, Output_IN_3, Output_EN_1, Output_EN_2, Output_EN_3,
    DBG_POST_CMD, DBG_POST_ERROR, DBG_CRC, S);
}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
